pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm test

    - step:
        name: Deploy to dev
        deployment: staging
        script:
          - echo "Deploying staging"
          - pipe: atlassian/ssh-run:0.2.5
            variables:
              SSH_USER: $DEPLOYMENT_USER
              SERVER: $DEPLOYMENT_SERVER
              SSH_KEY: $DEPLOYMENT_KEY
              MODE: 'script'
              COMMAND: $DEPLOYMENT_SCRIPT_PATH
              ENV_VARS: 'NODE_ENV=development'
          - echo "Deployed staging"